CREATE TABLE user (
  id            VARCHAR(255) GENERATED BY DEFAULT AS IDENTITY,
  admin         BOOLEAN NOT NULL,
  avatar_url    VARCHAR(255),
  description   VARCHAR(255),
  first_name    VARCHAR(255),
  last_name     VARCHAR(255),
  location      VARCHAR(255),
  password_hash VARCHAR(255),
  username      VARCHAR(255),
  PRIMARY KEY (id)
);

CREATE TABLE ad (
  id          VARCHAR(255) GENERATED BY DEFAULT AS IDENTITY,
  created_at  TIMESTAMP,
  created_by  VARCHAR(255),
  description VARCHAR(255),
  location    VARCHAR(255),
  photo_url   VARCHAR(255),
  points      DECIMAL(19, 2),
  title       VARCHAR(255),
  type        INTEGER,
  PRIMARY KEY (id)
);

CREATE TABLE message (
  id         VARCHAR(255) GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMP,
  created_by VARCHAR(255),
  text       VARCHAR(255),
  thread_id  VARCHAR(255),
  PRIMARY KEY (id)
);

CREATE TABLE message_thread (
  id         VARCHAR(255) GENERATED BY DEFAULT AS IDENTITY,
  ad_id      VARCHAR(255),
  created_by VARCHAR(255),
  title      VARCHAR(255),
  PRIMARY KEY (id)
);

CREATE TABLE message_thread_party (
  message_thread_id VARCHAR(255) NOT NULL,
  user_id           VARCHAR(255) NOT NULL
);

ALTER TABLE message_thread_party
  ADD CONSTRAINT fk_message_thread_party_user_id
FOREIGN KEY (user_id) REFERENCES user;

ALTER TABLE message_thread_party
  ADD CONSTRAINT fk_message_thread_party_message_thread_id
FOREIGN KEY (message_thread_id) REFERENCES message_thread;

CREATE TABLE transaction (
  id             VARCHAR(255) GENERATED BY DEFAULT AS IDENTITY,
  ad_id          VARCHAR(255),
  amount         DECIMAL(19, 2),
  beneficiary_id VARCHAR(255),
  created_at     TIMESTAMP,
  description    VARCHAR(255),
  remitter_id    VARCHAR(255),
  PRIMARY KEY (id)
);


